# Generated by Django 5.1.2 on 2024-11-22 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habito',
            name='dias_semana',
        ),
        migrations.RemoveField(
            model_name='habito',
            name='recordatorio_hora',
        ),
        migrations.AddField(
            model_name='habito',
            name='hora_recordatorio',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
