# Generated by Django 5.1.2 on 2024-11-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habito_dias_semana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habito',
            name='hora_recordatorio',
            field=models.TimeField(),
        ),
    ]
