# Generated by Django 5.1.2 on 2024-11-23 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0003_alter_habito_hora_recordatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habito',
            name='hora_recordatorio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habito',
            name='rango_tiempo_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='habito',
            name='rango_tiempo_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
