# Generated by Django 5.1.2 on 2024-11-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habito_hora_recordatorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='es_random',
            field=models.BooleanField(default=False),
        ),
    ]
